### ISSUE TITLE
Backward incompatibility of 0.17.0

### ISSUE THREAD

**Issue by catostrophe** [softwaremill/magnolia#266]
#257 has broken the backward compatibility of `magnolia`.

When I bumped version, I got a runtime error in a lib dependent on 0.16.0:
```
java.lang.NoSuchMethodError: 'magnolia.Param magnolia.Param$.apply(java.lang.String, int, boolean, magnolia.CallByNeed, magnolia.CallByNeed, java.lang.Object[])'
```

The newly added param should have been with the default value.

**Comment by joroKr21** [comment]
To promise backwards compatibility we would have to release 1.0

**Comment by catostrophe** [comment]
Magnolia has become a widely used library. The thing is that in a relatively small project it comes as a transitive dependency from 4 different libs.

If only one lib updates magnolia to 0.17.0, and the others don't come up with new releases, the whole app may be spoilt silently (will break at runtime). That's what really happened.

It doesn't cost much to support backward compatibility when you add a new argument such as an array of annotations.

**Comment by joroKr21** [comment]
I'm not even against releasing 1.0 but if we go through with #247 and #256 they will for sure not be binary compatible.
And the only way to be sure is to add MiMa to the build.

**Comment by propensive** [comment]
Thanks for reporting, @catostrophe. I want to move to version 1.0 quite soon now, though it does need a bit of admin work, which I haven't had time for.

**Comment by propensive** [comment]
#247 _can_ actually be binary compatible, as the methods aren't part of any binary API. But in any case, I would support `split` and `join` as aliases for `dispatch` and `combine`.
