### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by lukaszlenart** [softwaremill/magnolia#286]

**Comment by sakoht** [comment]
Is there a build available for Scala 2.13?

I see 2.11 and 2.12 on Maven Central:
https://search.maven.org/search?q=g:com.softwaremill

Another location?

**Comment by lukaszlenart** [comment]
I've just pushed 1.0.0-M1 - it should be available in the Central soon
https://github.com/softwaremill/magnolia/releases/tag/v1.0.0-M1

**Comment by lukaszlenart** [comment]
v1.0.0-M2 is out 🎉

**Comment by adamw** [comment]
I'd release 1.0 for scala 2 & scala 3 in its current form, to have a stable release.

Further improvements (such as finishing the `macrolia` branch for scala 3 or config improvements for scala 2) can go into a magnolia 2.0 release - the versioning scheme is ready :)

cc @lukaszlenart @KacperFKorban @joroKr21

**Comment by adamw** [comment]
Released both for scala 2 and scala 3 :)
