### ISSUE TITLE
The scala.deprecated annotation is not available through CaseClass.annotations

### ISSUE THREAD

**Issue by adamw** [softwaremill/magnolia#322]

**Comment by KacperFKorban** [comment]
@adamw Do You have a snippet?

**Comment by adamw** [comment]
Yes I'll prepare one, just wanted to make a note as I've got some WIP code in tapir that I want to finish first :) (and this came up during debugging said code)

**Comment by adamw** [comment]
@KacperFKorban here's a test: https://github.com/softwaremill/magnolia/pull/323 (for fields, it works when the annotation is on a class)
