### ISSUE TITLE
Remove scala-reflect from compile-time dependencies

### ISSUE THREAD

**Issue by adamw** [softwaremill/magnolia#326]
It is pulled in transitively via mercator. Instead, it should be marked as provided.

Maybe it would be possible to remove the mercator dependency alltogether?

**Comment by joroKr21** [comment]
I see a couple of options for removing `mercator`:
 * Roll our own `Monad` or better yet `Applicative` type class
 * Have `constructMonadic` take polymorphic `pure` and `flatMap` functions as arguments
 * Remove `constructMonadic` altogether (does it exist for Scala 3?)

**Comment by KacperFKorban** [comment]
In Scala 3 we have our own `Monad`. It was supposed to be a temporary solution.

**Comment by adamw** [comment]
I think having a self-contained project w/ a `Monad`/`Monadic` construct would be the most user-friendly version. There is `constructMonadic` in the scala3 version, but without a dependency on mercator (or any other dependency)

**Comment by joroKr21** [comment]
That will break binary compatibility again 😞

**Comment by joroKr21** [comment]
I'm not sure we can even update Mercator without breaking binary compatibility

**Comment by adamw** [comment]
@joroKr21 We're changing the group id, the package, so until we release 1.0 I don't think binary compatibility is a problem? Quite the contrary, now is the time to break things, no? :)

**Comment by joroKr21** [comment]
> Quite the contrary, now is the time to break things, no? :)

On the one hand yes, but on the other hand users still complain when it's broken: #266
The problem is that Magnolia is very close to the dependency root.

**Comment by adamw** [comment]
@joroKr21 but that's 0.17, 1.0 will never be a drop-in replacement for 0.17, 0.16 or any other version, even if it's only because of the new package name :)
